cyjz_web/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using MH.Rescue.BIZ;

namespace MH.Rescue.Web.Controllers
{
    public class ArticleController : BaseController
    {
        /// <summary>
        /// 显示“学术”首页
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            ViewBag.CurrentUser = CurrentUser;
            return View();
        }

        /// <summary>
        /// 显示学术文章列表
        /// </summary>
        /// <returns></returns>
        public ActionResult ArticleList()
        {
            var all = ArticleMgr.GetArticles();
            return View(all);
        }

        /// <summary>
        /// 显示搜索页面
        /// </summary>
        /// <returns></returns>
        public ActionResult Search()
        {
            return View();
        }

        /// <summary>
        /// 提交学术查询
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SubmitSearch()
        {
            var title = Request.Form["title"];
            //var type = Request.Form["type"];
            var fromDT = DateTime.Parse(Request.Form["fromDT"]);
            var toDT = DateTime.Parse(Request.Form["toDT"]);
            var author = Request.Form["author"];
            var author_dept = Request.Form["author_dept"];

            ArticleType? artile_type = null;
            //if (type == "1")
            //    artile_type = ArticleType.学术类;
            //else if (type == "2")
            //    artile_type = ArticleType.科普类;

            //ViewBag.Article_List = ArticleMgr.QueryArticles(title, artile_type, fromDT, toDT, author, author_dept);

            ViewBag.News_List = NewsMgr.QueryNews(title, fromDT, toDT, author, author_dept);

            if (string.IsNullOrEmpty(author) == true
                && string.IsNullOrEmpty(author_dept) == true)
                ViewBag.Cds_List = CdsMgr.QueryCds(title);

            return View("SearchResult");
        }

        /// <summary>
        /// 显示学术文章详情
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Detail(int id)
        {
            ViewBag.CurrentUser = CurrentUser;
            if (CurrentUser != null)
                ViewBag.Collection = AccountMgr.GetUserCollection(CurrentUser.id, ContentType.文章, id);
            var obj = ArticleMgr.GetArticle(id);
            return View("Detail", obj);
        }

        /// <summary>
        /// 显示新文章编辑页面
        /// </summary>
        /// <returns></returns>
        public ActionResult New()
        {
            ViewBag.CurrentUser = CurrentUser;
            return View();
        }

        /// <summary>
        /// 提交新文章，包括附件
        /// </summary>
        /// <param name="article"></param>
        /// <param name="file"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SubmitArticle([Bind]article article, HttpPostedFileBase file)
        {
            // 判断 文章标题是否为空
            if (string.IsNullOrEmpty(article.title) == true)
            {
                return Content("文章标题不可为空");
            }

            // 判断 是否选择了文章附件
            else if (file == null)
            {
                return Content("未选择文章附件");
            }

            else
            {
                // 判断文章的文件类型，支持 pdf/caj/doc/docx 格式  //by XW
                /*
                var ext = System.IO.Path.GetExtension(file.FileName);
                if ((ext != ".pdf") & (ext != ".caj") & (ext != ".doc") & (ext != ".docx"))
                {
                    return Content("文章附件格式有误，请重新选择，支持 pdf/caj/doc/docx 格式");
                }
                */

                // 判断文章的文件大小，支持小于20MB的
                /*var filesize = file.ContentLength;
                if (filesize >= 20971520)
                {
                    return Content("文章附件过大，请选择20MB以下的文件");
                }*/

                // 先添加发表文章申请
                var apply = new article_apply()
                {
                    apply_user_id = CurrentUser.id,
                    apply_user_name = CurrentUser.name,
                    apply_status = ArticleApplyStatusType.待审批, // 设置为待审批状态 by XW
                    apply_dt = DateTime.Now,
                };
                apply = ArticleMgr.InsertArticleApply(apply);

                // 记录申请信息
                article.apply_id = apply.id;

                article.publish_dt = DateTime.Now; // 只是为了避免数据库错误

                // 处理附件信息
                article.file_path = file.FileName;
                article.file_size = file.ContentLength;
                article.file_type = file.ContentType;
               

                ArticleMgr.InsertArticle(article); // 保存文章记录，为了获取id

                // 保存附件到服务器文件夹
                var folder = "~/FileUpload/article/" + article.id.ToString() + "/";
                System.IO.Directory.CreateDirectory(Server.MapPath(folder));
                file.SaveAs(Server.MapPath(folder + file.FileName));

                return Content("OK");
            }
        }

        /// <summary>
        /// 提交文章评论
        /// </summary>
        /// <param name="id"></param>
        /// <param name="content"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SubmitArticleComments(int id, string content)
        {
            if (string.IsNullOrEmpty(content) == true)
                return Content("评论内容不可为空。");

            var obj = new article_comments()
            {
                article_id = id,
                comments = content,
                user_id = CurrentUser.id,
                user_name = CurrentUser.name,
                created_dt = DateTime.Now
            };
            ArticleMgr.InsertArticleComments(obj);

            #region 发送消息通知给相关用户（apply user和comments user）
            var temp_user_list = new List<int>();

            var article = ArticleMgr.GetArticle(id);
            if (CurrentUser.id != article.article_apply.apply_user_id) // 不应该通知本人
            {
                var msg = new message()
                {
                    title = "文章讨论",
                    message_content = string.Format("我回复了您发布的文章《{0}》：{1}", article.title, content),
                    message_sender_id = CurrentUser.id,
                    message_sender_name = CurrentUser.name,
                    message_receiver_id = article.article_apply.apply_user_id,
                    message_receiver_name = article.article_apply.apply_user_name,
                };
                SystemMgr.InsertMessage(msg);
                temp_user_list.Add(msg.message_receiver_id);
            }
            foreach (var comments in article.article_comments.Where(t => t.user_id != CurrentUser.id)) // 通知其他用户
            {
                if (temp_user_list.Contains(comments.user_id) == true) // 不重复通知同一个用户（回复多次的）
                    continue;

                var msg2 = new message()
                {
                    title = "文章讨论",
                    message_content = string.Format("我回复您参与讨论的文章《{0}》：{1}", article.title, content),
                    message_sender_id = CurrentUser.id,
                    message_sender_name = CurrentUser.name,
                    message_receiver_id = comments.user_id,
                    message_receiver_name = comments.user_name,
                };
                SystemMgr.InsertMessage(msg2);
                temp_user_list.Add(msg2.message_receiver_id);
            }
            #endregion

            return Content("OK");
        }

        /// <summary>
        /// 删除文章评论
        /// </summary>
        /// <param name="id"></param>
        /// <param name="comments_id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteArticleComments(int id, int comments_id)
        {
            ArticleMgr.DeleteArticleComments(comments_id);
            return Content("OK");
        }
    }
}

cyjz_web/Controllers/TeachingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using MH.Rescue.BIZ;

namespace MH.Rescue.Web.Controllers
{
    public class TeachingController : BaseController
    {
        #region 直播（Teaching_Liv）


        /// <summary>
        /// 显示直播（Liv）详情
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult LivDetail(int id)
        {
            ViewBag.CurrentUser = CurrentUser;
            ViewBag.Comments = TeachingLivMgr.GetTeachingComments(id, 1);
            var obj = TeachingLivMgr.GetTeachingLiv(id);
            return View(obj);
        }

        /// <summary>
        /// 显示直播的已报名用户列表页面
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult LivApplyList(int id)
        {
            var list = TeachingLivMgr.GetTeachingLivApplyList(id);
            return View(list);
        }

        /// <summary>
        /// 提交教学直播报名申请
        /// </summary>
        /// <param name="liv_id"></param>
        /// <param name="user_id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SubmitTeachingApply(int liv_id, int user_id)
        {
            // 获得直播课程的最大报名数 和 已报名数
            //var obj = TeachingLivMgr.GetTeachingLive(liv_id);
            //int a_count = obj.apply_count;
            //int a_max = obj.apply_max;
            // 已报名数 小于 最大报名数
            //if (a_count < a_max)
           // {
                var obj1 = new teaching_apply()
                {
                    teaching_id = liv_id,
                    user_id = user_id,
                    created_dt = DateTime.Now
                };
                TeachingLivMgr.InsertTeachingApply(obj1);
                return Content("OK");

           // }
           // else return Content("KO");  // 已报名数 大于等于 最大报名数
            
        }

        /// <summary>
        /// 删除教学直播报名申请
        /// </summary>
        /// <param name="apply_id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteTeachingApply(int apply_id)
        {
            TeachingLivMgr.DeleteTeachingApply(apply_id);
            return Content("OK");
        }

        #endregion

        #region 视频回放、录播（Teaching_vod）


        /// <summary>
        /// 显示视频回放（Vod）详情
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult VodDetail(int id)
        {
            ViewBag.CurrentUser = CurrentUser;
            ViewBag.Comments = TeachingLivMgr.GetTeachingComments(id, 0);
            if (CurrentUser != null)
                ViewBag.Collection = AccountMgr.GetUserCollection(CurrentUser.id, ContentType.回放, id);

            var obj = TeachingVodMgr.GetTeachingVod(id);
            return View(obj);

        }
        #endregion

        #region 教学（Liv&Vod）公共部分

        /// <summary>
        /// 显示包含Framework7框架的完整首页（教学为默认页面）
        /// </summary>
        /// <returns></returns>
        public ActionResult Index(int id = 0)
        {
            return View();
        }

        /// <summary>
        /// 显示教学直播、回放列表
        /// </summary>
        /// <param name="tab"></param>
        /// <returns></returns>
        public ActionResult TeachingList(int tab = 1)
        {
            var list = TeachingLivMgr.GetTeachingLivs();
            ViewBag.TeachingVods = TeachingVodMgr.GetTeachingVods();
            ViewBag.TabIndex = tab;
            return View(list);
        }

        /// <summary>
        /// 显示教学视频查询页面
        /// </summary>
        /// <returns></returns>
        public ActionResult Search()
        {
            return View();
        }

        /// <summary>
        /// 提交教学视频查询操作
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SubmitSearch()
        {
            var title = Request.Form["title"];
            var fromDT = DateTime.Parse(Request.Form["fromDT"]);
            var toDT = DateTime.Parse(Request.Form["toDT"]);
            var teacher_name = Request.Form["teacher_name"];
            var teacher_org = Request.Form["teacher_org"];

            ViewBag.LivList = TeachingLivMgr.QueryTeachingLivs(title, fromDT, toDT, teacher_name, teacher_org);
            ViewBag.VodList = TeachingVodMgr.QueryTeachingVods(title, fromDT, toDT, teacher_name, teacher_org);

            return View("SearchResult");
        }

        /// <summary>
        /// 提交教学视频评论（Liv&Vod）
        /// </summary>
        /// <param name="id"></param>
        /// <param name="isLiv"></param>
        /// <param name="content"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SubmitTeachingComments(int id, int isLiv, string content)
        {
            if (string.IsNullOrEmpty(content) == true)
                return Content("评论内容不可为空。");

            var obj = new teaching_comments()
            {
                teaching_id = id,
                is_liv = isLiv,
                comments = content,
                user_id = CurrentUser.id,
                user_name = CurrentUser.name,
                created_dt = DateTime.Now
            };
            TeachingLivMgr.InsertTeachingComments(obj);

            return Content("OK");
        }

        /// <summary>
        /// 删除教学视频评论（Liv&Vod）
        /// </summary>
        /// <param name="comments_id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteTeachingComments(int comments_id)
        {
            TeachingLivMgr.DeleteTeachingComments(comments_id);
            return Content("OK");
        }
        #endregion

    }
}

cyjz_web/Views/Teaching/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <title>急诊互联 @ViewBag.Title</title>
    <link href="~/Contents/framework7/css/framework7-icons.css" rel="stylesheet" />

    @{
        var is_ios = Request.QueryString["android"] != "true"; // 根据平台加载不同的样式

        if (is_ios == true)
        {
            <link href="~/Contents/framework7/css/framework7.ios.css" rel="stylesheet" />
            <link href="~/Contents/framework7/css/framework7.ios.colors.css" rel="stylesheet" />
        }
        else
        {
            <link href="~/Contents/framework7/css/framework7.material.css" rel="stylesheet" />
            <link href="~/Contents/framework7/css/framework7.material.colors.css" rel="stylesheet" />
        }
    }

    <link href="~/Contents/fontawesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Contents/app-mainstyle.css" rel="stylesheet" />
</head>
<body>

    <div class="statusbar-overlay"></div>

    <div class="views tabs">
        <div id="view-1" class="view view-main tab active">
            <div class="pages">
                <div data-page="teaching-index" class="page navbar-fixed toolbar-fixed no-tabbar">
                    <div class="navbar bg-blue color-white">
                        <div class="navbar-inner">
                            <div class="left">
                                <a href="/teaching/search" class="link icon-only color-white">
                                    <i class="f7-icons">search</i>
                                </a>
                            </div>
                            <div class="center">
                                教学列表
                            </div>
                            <div class="right">
                            </div>
                            <div class="subnavbar sliding ios-only">
                                <div class="buttons-row">
                                    <a href="#tab1" class="button tab-link active">即将开始</a>
                                    <a href="#tab2" class="button tab-link">正在直播</a>
                                    <a href="#tab3" class="button tab-link">视频回放</a>
                                    <a href="#tab4" class="button tab-link">专家查房</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="toolbar tabbar android-only">
                        <div class="toolbar-inner">
                            <a href="#tab1" class="tab-link active">即将开始</a>
                            <a href="#tab2" class="tab-link">正在直播</a>
                            <a href="#tab3" class="tab-link">视频回放</a>
                            <a href="#tab4" class="tab-link">专家查房</a>
                        </div>

                    </div>

                    <div id="ptrTeaching" class="page-content with-subnavbar pull-to-refresh-content hide-bars-on-scroll">
                        <div class="pull-to-refresh-layer">
                            <div class="preloader"></div>
                            <div class="pull-to-refresh-arrow"></div>
                        </div>
                        <div id="teaching_list" class="tabs">
                            @Html.Action("TeachingList", "Teaching")
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="view-2" class="view view-2 tab">
            <div class="pages">
                @Html.Action("Index", "Article")
            </div>
        </div>
        <div id="view-3" class="view view-3 tab">
            <div class="pages">
                @Html.Action("Index", "PatientCase")
            </div>
        </div>
        <div id="view-4" class="view view-4 tab">
            <div class="pages">
                @Html.Action("Index", "kiosk")
            </div>
        </div>
        <div id="view-5" class="view view-5 tab">
            <div class="pages">
                @Html.Action("Index", "Account")
            </div>
        </div>

        <!-- Bottom Tabbar-->
        <div id="tabbar-main" class="toolbar tabbar tabbar-labels toolbar-bottom">
            <div class="toolbar-inner">
                <a href="#view-1" class="tab-link active">
                    <i class="icon f7-icons active">
                        videocam_round_fill
                        @*<span class="badge bg-red">2</span>*@
                    </i>
                    <span class="tabbar-label">教学</span>
                </a>
                <a href="#view-2" class="tab-link">
                    <i class="icon f7-icons">book_fill</i>
                    <span class="tabbar-label">学术</span>
                </a>
                <a href="#view-3" class="tab-link">
                    <i class="icon f7-icons">world_fill</i>
                    <span class="tabbar-label">会诊</span>
                </a>
                <a href="#view-4" class="tab-link">
                    <i class="icon f7-icons">briefcase_fill</i>
                    <span class="tabbar-label">自助问诊</span>
                </a>
                <a href="#view-5" class="tab-link" onclick="ReloadMyAccount()">
                    <i class="icon f7-icons">person_fill</i>
                    <span class="tabbar-label">我的</span>
                </a>
            </div>
        </div>
    </div>

    @Html.Partial("_Signin")

    <script src="~/Contents/framework7/js/framework7.js"></script>
    <script src="~/Contents/app-main-ios.js"></script>
    <script src="~/Contents/app-account.js"></script>
    <script src="~/Contents/app-teaching.js"></script>
    <script src="~/Contents/app-article.js"></script>
    <script src="~/Contents/app-news.js"></script>
    <script src="~/Contents/app-patientcase.js"></script>
    <script src="~/Contents/js_sdk20170302.js"></script>

    <!--MOB SHARE BEGIN-->
    <script>
        mobShare.config( {
            appkey: '1e8f6959e1a08', // appkey
             params: {
                 url: window.location.href,  // 分享链接
                 title: '来自【急诊互联】www.mee120.com', // 分享标题
            }
        } );
    </script>

    <div class="-mob-share-ui" style="display: none">
        <ul class="-mob-share-list">
            <li class="-mob-share-weibo"><p>新浪微博</p></li>
            <li class="-mob-share-tencentweibo"><p>腾讯微博</p></li>
            <li class="-mob-share-qzone"><p>QQ空间</p></li>
            <li class="-mob-share-qq"><p>QQ好友</p></li>
            <li class="-mob-share-renren"><p>人人网</p></li>
            <li class="-mob-share-weixin"><p>微信</p></li>
        </ul>
    </div>
    <div class="-mob-share-ui-bg"></div>
    <script id="-mob-share" src="http://f1.webshare.mob.com/code/mob-share.js?appkey=1e8f6959e1a08"></script>

    <!--MOB SHARE END-->

    <div class="popover popover-menu-share modal-in" style="width:200px;">
        <div class="popover-angle on-bottom"></div>
        <div class="popover-inner">
            <div class="list-block">
                <ul>
                    <li class="-mob-share-weibo"><a href="#" class="list-button item-link">新浪微博</a></li>
                    <li class="-mob-share-weixin"><a href="#" class="list-button item-link">微信好友</a></li>
                    <li class="-mob-share-weixin"><a href="#" class="list-button item-link">微信朋友圈</a></li>
                    <li class="-mob-share-qq"><a href="#" class="list-button item-link" >QQ好友</a></li>
                    <li class="-mob-share-qzone"><a href="#" class="list-button item-link">QQ空间</a></li>
                    <li><a href="mailto:?&subject=内容分享自急诊互联App&body=急诊互联 www.mee120.com " class="list-button item-link external">邮件</a></li>
                    <li><a href="sms:?&body=内容分享自急诊互联App www.mee120.com &body=急诊互联  www.mee120.com " class="list-button item-link external">短信</a></li>
                </ul>
            </div>
        </div>
    </div>


</body>
</html>

cyjz_web/Views/Teaching/LivApplyList.cshtml
@using MH.Rescue.BIZ
@model List<teaching_apply>

@{
    var user = ViewBag.CurrentUser as user_account;
}
<div data-page="liv-apply-list" class="page navbar-fixed no-tabbar page-on-center">

    <div class="navbar bg-blue color-white">
        <div class="navbar-inner">
            <div class="left">
                <a href="#" class="back link icon-only color-white">
                    <i class="icon icon-back color-white"></i>
                </a>
            </div>
            <div class="center">
                已报名观众列表
            </div>
            <div class="right">
            </div>
        </div>
    </div>

    <div class="page-content">
        @if (Model == null || Model.Count == 0)
            {
            <div style="padding:150px 20px; text-align:center;">
                <i class="f7-icons" style="font-size:120px; opacity:0.2;">persons</i>
                <div style="padding:15px;">
                    目前没有已报名的观众
                </div>
            </div>
            }
            else
            {
            <div class="list-block media-list no-margin-top-2">
                <ul>
                    @foreach (var item in Model)
                        {
                        <li>
                            <div class="item-content">
                                <div class="item-media">
                                    <img src="~/Contents/image/avatar/default/@(item.user_account.avatar)" width="44">
                                </div>
                                <div class="item-inner">
                                    <div class="item-title-row">
                                        <div class="item-title">@item.user_account.name @item.user_account.title</div>
                                    </div>
                                    <div class="item-subtitle" style="opacity:0.5;">@item.user_account.hospital_name @item.user_account.department_name</div>
                                </div>
                            </div>
                        </li>
                        }
                </ul>
            </div>
            }
    </div>

</div>

cyjz_web/Views/Teaching/LivList.cshtml
@using MH.Rescue.BIZ
@model List<teaching_liv>

@if (Model == null || Model.Count == 0)
{
    <div style="padding:150px 20px; text-align:center;">
        <i class="f7-icons" style="font-size:120px; opacity:0.2;">videocam_round_fill</i>
        <div style="padding:15px;">
            暂无教学直播
        </div>
    </div>
}
else
{
    <div class="list-block media-list no-margin-top-2">
        <ul>
            @foreach (var item in Model)
            {
                <li>
                    <a href="/teaching/livdetail?id=@(item.id)" class="item-link item-content">
                        <div class="item-media">
                            @if (item.cmn_image == null)
                            {
                                <div style="width:80px; height:80px; background-color:#ddd; text-align:center; vertical-align:middle;">
                                    <span class="fa fa-video-camera color-white" style="font-size:45px; padding-top:20px;"></span>
                                </div>
                            }
                            else
                            {
                                <div style="background-image:url('/FileUpload/Teaching_liv/@(item.id)/@(item.cmn_image.thumbnail)'); background-size:cover; width:80px; height:80px;"></div>
                            }
                        </div>
                        <div class="item-inner">
                            <div class="item-title-row">
                                <div class="item-title">@item.title</div>
                            </div>
                            <div class="item-subtitle">@item.teacher_name · @item.start_dt.ToString(MH.CMN.Const.DateTimeFormat)</div>
                            <div class="item-text">@item.description</div>
                        </div>
                    </a>
                </li>
            }
        </ul>
    </div>
}

cyjz_web/Views/Teaching/Search.cshtml
<div data-page="teaching-search" class="page navbar-fixed no-toolbar no-tabbar no-main-tabbar page-on-center">

    <div class="navbar bg-blue color-white">
        <div class="navbar-inner">
            <div class="left">
                <a href="/teaching/index" class="back link icon-only color-white">
                    <i class="icon icon-back color-white"></i>
                </a>
            </div>
            <div class="center">
                教学查询
            </div>
            <div class="right">
            </div>
        </div>
    </div>

    <div class="page-content">

        <form id="formTeachingSearch" class="list-block">
            <ul>
                <li>
                    <div class="item-content">
                        <div class="item-inner">
                            <div class="item-title label">标题或关键字</div>
                            <div class="item-input">
                                <input type="text" name="title" placeholder="">
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="item-content">
                        <div class="item-inner">
                            <div class="item-title label">发布日期自</div>
                            <div class="item-input">
                                <input type="date" name="fromDT" value="@(DateTime.Today.AddMonths(-1).ToString("yyyy-MM-dd"))">
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="item-content">
                        <div class="item-inner">
                            <div class="item-title label">发布日期到</div>
                            <div class="item-input">
                                <input type="date" name="toDT" value="@(DateTime.Today.AddMonths(1).ToString("yyyy-MM-dd"))">
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="item-content">
                        <div class="item-inner">
                            <div class="item-title label">讲师姓名</div>
                            <div class="item-input">
                                <input type="text" name="teacher_name">
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="item-content">
                        <div class="item-inner">
                            <div class="item-title label">讲师单位</div>
                            <div class="item-input">
                                <input type="text" name="teacher_org">
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </form>

        <div class="content-block">
            <div class="row">
                <div class="col-50">
                    <a href="#" class="button button-big button-fill color-blue button-raised active" onclick="TeachingSearch()">查询</a>
                </div>
                <div class="col-50">
                    <a href="#" class="button button-big button-raised" onclick="document.getElementById('formTeachingSearch').reset()">重置</a>
                </div>
            </div>
        </div>

    </div>

</div>

cyjz_web/Views/Teaching/TeachingList.cshtml
@using MH.Rescue.BIZ
@using System.Configuration
@model List<teaching_liv>

@{
    var tab = (int)ViewBag.TabIndex;
    var vods = ViewBag.TeachingVods as List<teaching_vod>;
    // 区分出专家查房和其它类型的视频回放（vod）
    var wardrounds_categoryid = int.Parse(ConfigurationManager.AppSettings["VodCategory_WardRounds"]);
    var wardrounds = vods.Where(t => t.category_id == wardrounds_categoryid).ToList();
    var other_vod = vods.Where(t => t.category_id != wardrounds_categoryid).ToList();
}

<div id="tab1" class="tab @(tab==1?"active":"")">
    @Html.Partial("LivList", Model.Where(t => t.start_dt > DateTime.Now).ToList())
</div>
<div id="tab2" class="tab @(tab==2?"active":"")">
    @Html.Partial("LivList", Model.Where(t => t.start_dt <= DateTime.Now && t.end_dt > DateTime.Now).ToList())
</div>
<div id="tab3" class="tab @(tab==3?"active":"")">
    @Html.Partial("VodList", other_vod)
</div>
<div id="tab4" class="tab @(tab==4?"active":"")">
    @Html.Partial("VodList", wardrounds)
</div>